apiVersion: autoscaling.aibrix.ai/v1alpha1
kind: PodAutoscaler
metadata:
  name: qwen257-prefill-autoscaler
  namespace: default
spec:
  scalingStrategy: KPA
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qwen257
  minReplicas: 0
  maxReplicas: 4
  metricsSources:
    - endpoint: aibrix-gpu-optimizer.aibrix-system.svc.cluster.local:8080
      metricSourceType: domain
      path: /metrics/default/qwen257
      protocolType: http
      targetMetric: vllm:deployment_replicas
      targetValue: "100"
